application: centralparkedu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: main.APPLICATION

- url: /
  static_files: static/html/index.html
  upload: static/html/index\.html

- url: /login
  static_files: static/html/login.html
  upload: static/html/login\.html

- url: /signup
  static_files: static/html/signup.html
  upload: static/html/signup\.html

- url: /home
  static_files: static/html/home.html
  upload: static/html/home\.html

- url: /checkout
  static_files: static/html/checkout.html
  upload: static/html/checkout\.html

- url: /about
  static_files: static/html/about.html
  upload: static/html/about\.html
  
- url: /controllers
  static_dir: controllers

- url: /lib
  static_dir: lib

- url: /static
  static_dir: static

- url: /.*
  script: main.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: protorpc
  version: latest
- name: ssl
  version: latest
- name: webapp2
  version: latest
