application: centralparkedu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: main.APPLICATION

- url: /
  static_files: index.html
  upload: index\.html

- url: /officers
  static_files: officerList.html
  upload: officerList\.html

- url: /login
  static_files: login.html
  upload: login\.html

- url: /signup
  static_files: signup.html
  upload: signup\.html

- url: /home
  static_files: home.html
  upload: home\.html

- url: /checkout
  static_files: checkout.html
  upload: checkout\.html

- url: /about
  static_files: about.html
  upload: about\.html
  
- url: /controllers
  static_dir: controllers

- url: /lib
  static_dir: lib

- url: /static
  static_dir: static

- url: /.*
  script: main.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: protorpc
  version: latest
- name: ssl
  version: latest
- name: webapp2
  version: latest
