application: centralparkedu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: main.APPLICATION

- url: /officers
  static_files: frontEnd/officerList.html
  upload: frontEnd/officerList\.html

- url: /frontEnd
  static_dir: frontEnd

- url: /lib
  static_dir: lib

- url: /static
  static_dir: static

- url: /.*
  script: main.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: protorpc
  version: 1.0
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
